- name: Update and upgrade yum packages
  yum:
    update_cache: yes

- name: Install Apache
  yum:
    name: httpd
    state: present

- name: Install MySQL
  yum:
    name: mysql-server
    state: present

- name: Install PHP and necessary extensions
  yum:
    name: php
    state: present

- name: Restart Apache
  service:
    name: httpd
    state: restarted
